# Generated by Django 5.0.7 on 2024-08-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={},
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(default='news/default.jpeg', upload_to='news/images'),
        ),
    ]
